CREATE PROCEDURE listar_articulos

AS
BEGIN 
	SET NOCOUNT ON; -- ACTIVAR, PARA QUE NO SALGAN EL NUMERO DE LINEAS AFECTADAS

	SELECT A.Id -- SE MUESTRA EL ID
	, A.Nombre -- SE MUESTRA EL NOMBRE 
	, A.Precio -- SE MUESTRA EL PRECIO 
	FROM dbo.Articulo A -- DE LA TABLA ARTICULO

	SET NOCOUNT OFF; -- SE DESACTIVA SIEMPRE ANTES DE FINALIZAR
END