
CREATE PROCEDURE insertar_articulo
(
 @Nombre VARCHAR (124) -- PARAMETROS DE ENTRADA
 , @Precio MONEY
)
AS
BEGIN 
	SET NOCOUNT ON; -- ACTIVAR, PARA QUE NO SALGAN EL NUMERO DE LINEAS AFECTADAS

		IF (@Nombre IS NULL OR -- SE EVITA QUE SEA NULO
			@Nombre NOT LIKE '%[a-z]%' AND -- SE VALIDA QUE SEAN LETRAS
			@Nombre NOT LIKE '%-%'  -- O QUE CONTENGA UN GUION
			)
		BEGIN
			PRINT 'El nombre no es valido' -- EN CASO DE QUE NO, SE IMPRIME UN ERROR
			RETURN;
		END;

		IF (@Precio IS NULL OR -- SE EVITA QUE SEA NULO
			@Precio <= 0 -- O SI ES MENOR O IGUAL A 0
			) 
		BEGIN
			PRINT 'El precio no es valido' -- EN CASO DE QUE NO, SE IMPRIME UN ERROR
			RETURN;
		END;

	INSERT INTO dbo.Articulo -- SE INSERTA A LA TABLA EL ARTICULO
	VALUES (@Nombre, @Precio)
	PRINT 'Dato agregado'

	SET NOCOUNT OFF; -- SE DESACTIVA SIEMPRE ANTES DE FINALIZAR
END